# Generated by Django 5.0.7 on 2025-09-21 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('BRONZE', 'Bronze Badge'), ('SILVER', 'Silver Badge'), ('GOLD', 'Gold Badge'), ('PLATINUM', 'Platinum Badge'), ('ECO_CHAMPION', 'Eco Champion'), ('TREE_LOVER', 'Tree Lover'), ('RECYCLING_HERO', 'Recycling Hero'), ('CLEANUP_MASTER', 'Cleanup Master'), ('AWARENESS_ADVOCATE', 'Awareness Advocate'), ('ENERGY_SAVER', 'Energy Saver'), ('EVENT_PARTICIPANT', 'Event Participant'), ('TEAM_PLAYER', 'Team Player')], max_length=50)),
                ('threshold_points', models.IntegerField(blank=True, null=True)),
                ('threshold_activities', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=50)),
                ('icon', models.CharField(default='🏆', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('student_id', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.CharField(blank=True, choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Graduate', 'Graduate'), ('Faculty', 'Faculty')], max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('total_points', models.IntegerField(default=0)),
                ('total_carbon_saved', models.FloatField(default=0.0)),
                ('certificates_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('BRONZE', 'Bronze Badge'), ('SILVER', 'Silver Badge'), ('GOLD', 'Gold Badge'), ('PLATINUM', 'Platinum Badge'), ('ECO_CHAMPION', 'Eco Champion'), ('TREE_LOVER', 'Tree Lover'), ('RECYCLING_HERO', 'Recycling Hero'), ('CLEANUP_MASTER', 'Cleanup Master'), ('AWARENESS_ADVOCATE', 'Awareness Advocate'), ('ENERGY_SAVER', 'Energy Saver'), ('EVENT_PARTICIPANT', 'Event Participant'), ('TEAM_PLAYER', 'Team Player')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
