# Generated by Django 5.2.6 on 2025-09-21 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('TREE', 'Tree Plantation'), ('RECYCLE', 'Recycling'), ('CLEANUP', 'Clean-up Drive'), ('AWARENESS', 'Awareness Campaign'), ('ENERGY_SAVING', 'Energy Saving Initiative')], max_length=50)),
                ('quantity', models.FloatField(default=1.0, help_text='e.g., number of trees, kg of recycling, hours of awareness')),
                ('description', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('points_awarded', models.IntegerField(default=0)),
                ('carbon_saved_kg', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from admin on rejection.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_saved_kg', models.FloatField()),
                ('points_earned', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activitysubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
